package com.jdandroid.core.texts

/**
 * German fallback texts of the hoster layer for [com.jdandroid.core.Texts].
 * Every key exists verbatim in `res/values/strings_hoster.xml` and translated
 * in `res/values-en/strings_hoster.xml` (checked by `TextsTest`).
 *
 * Account tiers ("Premium", "Ultimate", "Premium/Access") stay untranslated:
 * `Account.hasPremium` compares against them. Texts.t has no plurals, so
 * durations use unit abbreviations (h, min, s).
 */
object HosterTexts {
    val texts: Map<String, String> = mapOf(
        // Shared (Hoster.kt)
        "hoster_free_status" to "Free",
        "hoster_free_status_unsupported" to "Free (Downloads nicht möglich)",
        "hoster_free_unsupported" to "Free-Download wird von diesem Hoster nicht unterstützt",
        "hoster_no_check_possible" to "Keine Prüfung möglich",
        "hoster_file_offline" to "Datei ist offline",
        "hoster_file_not_found" to "Datei nicht gefunden",
        "hoster_unknown_error" to "Unbekannter Fehler",
        "hoster_unexpected_response" to "Unerwartete Antwort",
        "hoster_empty_server_response" to "Leere Antwort vom Server",
        "hoster_api_no_response" to "Keine Antwort der API",
        "hoster_http_status" to "HTTP %1\$d",
        "hoster_status_code" to "Status %1\$d",
        "hoster_http_status_unknown" to "HTTP %1\$d – Status unbekannt",
        "hoster_cloudflare_check_unknown" to "Cloudflare-Prüfung – Status unbekannt",
        "hoster_no_username" to "Kein Benutzername hinterlegt",
        "hoster_no_password" to "Kein Passwort hinterlegt",
        "hoster_no_api_key" to "Kein API-Key hinterlegt",
        "hoster_too_many_requests" to "Zu viele Anfragen (HTTP %1\$d)",
        "hoster_not_authenticated" to "Nicht angemeldet (HTTP %1\$d)",
        "hoster_access_blocked" to "Zugriff blockiert (HTTP 403)",
        "hoster_status_quota_unreadable" to "%1\$s · Kontingent nicht lesbar",
        "hoster_status_cdn_credit" to "%1\$s · CDN-Guthaben %2\$s",
        "hoster_duration_hours" to "%1\$d h",
        "hoster_duration_minutes" to "%1\$d min",
        "hoster_duration_seconds" to "%1\$d s",

        // ddownload
        "hoster_ddownload_account_hint" to "Empfohlen: API-Key aus dem ddownload-Konto (my.ddownload.com → API). Alternativ unten „Im Browser anmelden“ für Benutzername/Passwort – der Login verlangt ein CAPTCHA und geht nur im Browser.",
        "hoster_ddownload_invalid_link" to "Ungültiger ddownload-Link",
        "hoster_ddownload_cloudflare_blocked" to "ddownload: Zugriff von Cloudflare blockiert (HTTP %1\$d). Bitte später erneut versuchen oder im Browser einmal die Seite öffnen.",
        "hoster_ddownload_no_login" to "ddownload: keine Anmeldung hinterlegt. Entweder API-Key eintragen oder „Im Browser anmelden“ verwenden (Login verlangt ein CAPTCHA).",
        "hoster_ddownload_account_page_unreachable" to "ddownload: Kontoseite nicht erreichbar (HTTP %1\$d)",
        "hoster_ddownload_session_expired" to "ddownload: Browser-Session abgelaufen. Bitte unter Konten erneut „Im Browser anmelden“.",
        "hoster_ddownload_unexpected_api_response" to "ddownload: unerwartete API-Antwort",
        "hoster_ddownload_api_not_json" to "ddownload-API: keine JSON-Antwort (HTTP %1\$d)",
        "hoster_ddownload_api_error" to "ddownload: %1\$s",
        "hoster_ddownload_premium_required" to "ddownload benötigt ein Premium-Konto (unter Konten hinzufügen).",
        "hoster_ddownload_no_direct_link_hint" to "ddownload: kein Direktlink erhalten (HTTP %1\$d, %2\$s).",
        "hoster_ddownload_no_direct_link" to "ddownload: kein Direktlink erhalten (HTTP %1\$d)",
        "hoster_hint_limit_reached" to "Tageslimit erreicht oder Sperre – wird später erneut versucht",
        "hoster_hint_premium_only" to "Datei ist nur für Premium verfügbar",
        "hoster_hint_free_wait" to "Server verlangt Wartezeit (Free-Modus)",
        "hoster_hint_redirect_without_file" to "Weiterleitung ohne Datei",
        "hoster_hint_unexpected_response" to "unerwartete Antwort",
        "hoster_ddownload_file_page_unreachable" to "ddownload: Dateiseite nicht erreichbar (HTTP %1\$d)",
        "hoster_ddownload_captcha_browser" to "ddownload: Captcha (%1\$s) – nur im Browser lösbar",
        "hoster_ddownload_image_captcha" to "ddownload: Bild-Captcha – nur im Browser lösbar",
        "hoster_ddownload_captcha_rejected" to "ddownload: Captcha abgelehnt – bitte im Browser lösen",
        "hoster_ddownload_download_session_expired" to "ddownload: Download-Sitzung abgelaufen – wird erneut versucht",
        "hoster_ddownload_countdown_skipped" to "ddownload: Countdown nicht eingehalten",
        "hoster_ddownload_free_countdown" to "ddownload: Countdown vor dem Free-Download",
        "hoster_ddownload_free_locked" to "ddownload: Sperre bis zum nächsten Free-Download",
        "hoster_ddownload_maintenance" to "ddownload: Server in Wartung – später erneut",
        "hoster_ddownload_free_size_limit" to "ddownload: Free-Download nur bis %1\$s – für diese Datei ist ein Premium-Konto nötig",
        "hoster_ddownload_premium_only" to "ddownload: Datei ist nur mit Premium-Konto ladbar",
        "hoster_ddownload_limit_reached_hour" to "ddownload: Download-Limit erreicht – in einer Stunde erneut",
        "hoster_ddownload_no_download_url" to "ddownload lieferte keine Download-URL",
        "hoster_ddownload_no_download_url_premium" to "ddownload lieferte keine Download-URL (Premium nötig?)",

        // Rapidgator
        "hoster_rapidgator_account_hint" to "E-Mail und Passwort des Rapidgator-Kontos (Premium erforderlich).",
        "hoster_rapidgator_invalid_link" to "Ungültiger Rapidgator-Link",
        "hoster_rapidgator_restart_flow" to "Rapidgator: Ablauf neu starten",
        "hoster_rapidgator_unlock_rejected" to "Freischaltung abgelehnt: %1\$s",
        "hoster_rapidgator_captcha_page_redirect" to "Captcha-Seite nicht erreichbar (Weiterleitung)",
        "hoster_rapidgator_flow_not_accepted" to "Rapidgator: Free-Ablauf wird vom Server nicht anerkannt (%1\$s)",
        "hoster_rapidgator_download_not_possible" to "Rapidgator: Download derzeit nicht möglich",
        "hoster_rapidgator_captcha_page_unreachable" to "Rapidgator: Captcha-Seite nicht erreichbar (HTTP %1\$d)",
        "hoster_rapidgator_captcha_browser" to "Rapidgator: Captcha (Turnstile) – nur im Browser lösbar",
        "hoster_rapidgator_no_direct_link" to "Rapidgator: kein Direktlink erhalten (HTTP %1\$d)",
        "hoster_rapidgator_file_page_unreachable" to "Rapidgator: Dateiseite nicht erreichbar (HTTP %1\$d)",
        "hoster_rapidgator_no_free_offer" to "Rapidgator: Seite bietet keinen Free-Download an",
        "hoster_rapidgator_free_unavailable" to "Rapidgator: Free-Download derzeit nicht möglich (%1\$s)",
        "hoster_rapidgator_http_response" to "Rapidgator: Antwort HTTP %1\$d",
        "hoster_rapidgator_unexpected_response" to "Rapidgator: unerwartete Antwort",
        "hoster_rapidgator_free_wait" to "Rapidgator: Wartezeit vor dem Free-Download",
        "hoster_rapidgator_api_error" to "Rapidgator: %1\$s",
        "hoster_rapidgator_login_failed" to "Rapidgator-Login fehlgeschlagen",
        "hoster_rapidgator_check_needs_account" to "Prüfung erst mit Rapidgator-Konto",
        "hoster_rapidgator_premium_required" to "Rapidgator benötigt einen Premium-Account (unter Konten hinzufügen).",
        "hoster_rapidgator_no_download_url" to "Rapidgator lieferte keine Download-URL",
        "hoster_rapidgator_free_size_limit" to "Rapidgator: Datei zu groß für den Free-Modus (bis %1\$s) – Premium nötig",
        "hoster_rapidgator_premium_only" to "Rapidgator: Datei nur mit Premium-Konto ladbar",
        "hoster_rapidgator_subscribers_only" to "Rapidgator: Datei nur für Abonnenten dieses Anbieters ladbar",
        "hoster_rapidgator_next_free_in" to "Rapidgator: nächster Free-Download erst in %1\$s",
        "hoster_rapidgator_locked_retry_in" to "Rapidgator: Sperre, erneuter Versuch in %1\$s",
        "hoster_rapidgator_daily_limit" to "Rapidgator: Tageslimit im Free-Modus erreicht",
        "hoster_rapidgator_hourly_limit" to "Rapidgator: Stundenlimit im Free-Modus erreicht",
        "hoster_rapidgator_one_at_a_time" to "Rapidgator: im Free-Modus nur ein Download gleichzeitig",
        "hoster_rapidgator_temporarily_unavailable" to "Rapidgator: Datei vorübergehend nicht verfügbar",

        // 1fichier
        "hoster_onefichier_account_hint" to "API-Key aus den 1fichier-Kontoeinstellungen (Bereich „API“), Premium/Access nötig.",
        "hoster_onefichier_invalid_link" to "Ungültiger 1fichier-Link",
        "hoster_onefichier_maintenance" to "1fichier: Wartung – in 20 Minuten erneut",
        "hoster_onefichier_temporarily_blocked" to "1fichier: Zugriff vorübergehend gesperrt (HTTP %1\$d) – in 15 Minuten erneut",
        "hoster_onefichier_file_page_unreachable" to "1fichier: Dateiseite nicht erreichbar (HTTP %1\$d)",
        "hoster_onefichier_form_missing" to "1fichier: Download-Formular fehlt",
        "hoster_onefichier_confirm_in_browser" to "1fichier: Bestätigung im Browser nötig",
        "hoster_onefichier_no_direct_link" to "1fichier: kein Direktlink erhalten (HTTP %1\$d)",
        "hoster_onefichier_no_free_offer" to "1fichier: Seite bietet keinen Free-Download an",
        "hoster_onefichier_password_in_browser" to "1fichier: Datei ist passwortgeschützt – Passwort im Browser eingeben",
        "hoster_onefichier_free_countdown" to "1fichier: Countdown vor dem Free-Download",
        "hoster_onefichier_empty_response" to "Leere Antwort von 1fichier",
        "hoster_onefichier_api_error" to "1fichier: %1\$s",
        "hoster_onefichier_unexpected_response" to "1fichier: unerwartete Antwort (HTTP %1\$d)",
        "hoster_onefichier_check_no_response" to "Keine Antwort vom Link-Check",
        "hoster_onefichier_api_key_required" to "1fichier benötigt einen API-Key (unter Konten hinzufügen).",
        "hoster_onefichier_no_download_url" to "1fichier lieferte keine Download-URL",
        "hoster_onefichier_account_required" to "1fichier: Datei nur mit Konto ladbar (Besitzer sperrt Free-Download)",
        "hoster_onefichier_access_restricted" to "1fichier: Zugriff auf die Datei ist vom Besitzer eingeschränkt",
        "hoster_onefichier_bad_password" to "1fichier: Passwort falsch",
        "hoster_onefichier_next_free_in" to "1fichier: nächster Free-Download in %1\$s",
        "hoster_onefichier_ip_locked" to "1fichier: IP-Adresse gesperrt – Freigabe in einer Stunde",
        "hoster_onefichier_one_at_a_time" to "1fichier: im Free-Modus nur ein Download gleichzeitig je Adresse",
        "hoster_onefichier_no_free_slots" to "1fichier: derzeit keine freien Download-Plätze",
        "hoster_onefichier_too_fast" to "1fichier: Anfragen zu schnell – kurze Pause",
        "hoster_onefichier_server_error" to "1fichier: Serverfehler – in fünf Minuten erneut",
        "hoster_onefichier_free_overuse" to "1fichier: Free-Nutzung vorübergehend gesperrt (zu viele Downloads)",
        "hoster_onefichier_vpn_blocked" to "1fichier: Free-Download von Server-/VPN-Adressen gesperrt – VPN ausschalten oder Konto hinterlegen",
    )
}
